Repository during-budget/during-web, pull requests merged in 2023-02, with the labels that each got.

#70 feat: Update CategoryAPIs #69
  server/controllers/categories.js
Labels: Backend, Enhancement

#81 AmountDetail / Make it reusable - dispatch in onEdit
  client/src/components/Amount/AmountDetail.tsx
  client/src/components/Status/TotalStatus.tsx
Labels: Frontend, Enhancement

#86 fix: Rename 'ammount' to 'amount' #85
  server/controllers/budgets.js
  server/controllers/categories.js
  server/controllers/transactions.js
  server/models/Budget.js
  server/models/Transaction.js
  server/routes/budgets.js
Labels: Backend, Bug

#90 fix: Update DBudgetCategoryAPI #89
  server/controllers/budgets.js
Labels: Backend, Bug

#104 feat: Nav / Create bottom nav bar to Root
  client/src/index.tsx
  client/src/screens/Nav.module.css
  client/src/screens/Nav.tsx
Labels: Frontend, New Feature

#123 feat: Style / Set global style
  client/src/App.css
Labels: Frontend, New Feature
