Repository during-budget/during-web, pull requests merged in 2023-05, with the labels that each got.

#259 Budget / Find budget by date
  server/controllers/budgets.ts
Labels: Backend

#261 Transaction / Fix update error
  server/controllers/transactions.ts
Labels: Backend, Bug

#270 Asset / Create single asset C/U/D APIs
  server/controllers/assets.ts
  server/routes/assets.ts
Labels: Backend

#275 User / Create DUser API
  server/controllers/users.ts
  server/routes/users.ts
Labels: Backend

#279 AmountRing / Set dash for different screen size
  client/src/components/Budget/List/BudgetItem.tsx
  client/src/components/Budget/Status/TotalStatus.tsx
Labels: Frontend, Bug

#284 Carousel / Fix initial index setting
  client/src/components/UI/Carousel.tsx
Labels: New Feature, Bug

#286 CategoryStatus / Fix index bug (expense <-> income)
  client/src/components/Budget/Status/CategoryStatus.tsx
Labels: Frontend, Bug

#289 Ring / Remove filter & Add opacity animation
  client/src/components/Budget/Amount/AmountRing.module.css
  client/src/components/Budget/Amount/AmountRing.tsx
  client/src/components/Budget/Amount/Ring.tsx
  client/src/models/Amount.ts
Labels: Frontend, Bug

#290 Overlay / Change transition property for optimization
  client/src/components/Budget/Transaction/TransactionForm.module.css
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/UI/Overlay.module.css
Labels: Frontend, Enhancement

#293 Admin / Fix loading budgets error
  server/controllers/budgets.ts
Labels: Backend

#297 Admin / Remove test APIs
  server/controllers/test.ts
  server/routes/test.ts
Labels: Backend

#304 EmojiInput / Manage UI in store
  client/src/components/Asset/Editor/AssetCardEditor.tsx
  client/src/components/Budget/Category/CategoryEditItem.tsx
  client/src/components/Budget/Category/CategorySettingItem.tsx
  client/src/components/Budget/Category/DefaultCategoryEdit.tsx
  client/src/components/Budget/Input/EmojiInput.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/UI/EmojiInput.module.css
  client/src/components/UI/EmojiInput.tsx
  client/src/components/UI/EmojiOverlay.module.css
  client/src/components/UI/EmojiOverlay.tsx
  client/src/components/UI/Overlay.module.css
  client/src/components/User/Category/UserCategoryList.tsx
  client/src/screens/Budget.tsx
  client/src/screens/InitialSetting.tsx
  client/src/store/ui.ts
Labels: Frontend, Bug

#310 BudgetCategorySetting: Move to outside of TransactionForm
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/UI/Overlay.module.css
Labels: Frontend, Bug

#313 Transaction / return updated transactionScheduled #312
  server/controllers/transactions.ts
Labels: Backend

#315 Transaction / Change class to interface & Update dispatch
  client/src/components/Budget/Status/DateStatus.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/Budget/Transaction/TransactionItem.tsx
  client/src/components/Budget/Transaction/TransactionList.tsx
  client/src/components/Budget/Transaction/TransactionOption.tsx
  client/src/constants/date.ts
  client/src/models/Transaction.ts
  client/src/store/transaction.ts
  client/src/util/api/categoryAPI.ts
  client/src/util/api/transactionAPI.ts
  client/src/util/filter.ts
Labels: Frontend, Enhancement

#317 Transaction / Add updateAsset field
  client/src/components/Budget/Input/MemoInput.tsx
  client/src/components/Budget/Transaction/TransactionForm.module.css
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/store/transaction.ts
  client/src/util/api/transactionAPI.ts
  client/vite.config.ts
Labels: Frontend, New Feature

#331 ErrorBoundary / Change <Navigate /> to useNavigate()
  client/package.json
  client/src/App.tsx
  client/src/layout/ErrorBoundary.tsx
  client/src/screens/Auth.tsx
Labels: Frontend, Bug

#333 LoadingSpinner / Add loading spinner when get user log in
  client/public/assets/svg/cat_spinner.svg
  client/src/components/UI/LoadingSpinner.module.css
  client/src/components/UI/LoadingSpinner.tsx
  client/src/screens/Auth.module.css
  client/src/screens/Auth.tsx
Labels: Frontend, Enhancement

#339 feat: ChartSkin / Fetch setting data
  client/src/components/Budget/Amount/AmountRing.tsx
  client/src/components/User/Skin/ChartSkinSetting.tsx
  client/src/screens/Auth.tsx
  client/src/store/index.ts
  client/src/store/setting.ts
  client/src/store/user.ts
  client/src/util/api/settingAPI.ts
  client/src/util/api/userAPI.ts
Labels: Frontend, Enhancement

#352 TransactionForm / Add pending state
  client/src/App.css
  client/src/components/Budget/Category/BudgetCategorySetting.module.css
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/UI/ConfirmCancelButtons.module.css
  client/src/components/UI/ConfirmCancelButtons.tsx
Labels: Frontend, Enhancement

#361 AssetCardListEditor / Check if response exists in submitHandler
  client/src/components/Asset/Editor/AssetCardListEditor.tsx
Labels: Frontend, Bug

#368 Redirect / User modal for sns direct
  client/src/components/UI/Modal.module.css
  client/src/components/UI/Modal.tsx
  client/src/screens/Auth.tsx
  client/src/screens/Redirect.tsx
  client/src/screens/User.tsx
  client/src/store/ui.ts
Labels: New Feature, Enhancement

#369 User / Add delete user button
  client/src/screens/User.module.css
  client/src/screens/User.tsx
  client/src/util/api/userAPI.ts
Labels: Frontend, New Feature

#370 Auth / Show error message
  client/src/components/Auth/EmailForm.module.css
  client/src/components/Auth/EmailForm.tsx
  client/src/components/Auth/SNSForm.tsx
  client/src/components/UI/Inform.module.css
  client/src/components/UI/Inform.tsx
  client/src/components/UI/OverlayForm.tsx
  client/src/screens/Auth.tsx
  client/src/util/api/userAPI.ts
  client/src/util/error.ts
  client/src/util/validate.ts
Labels: Frontend, Enhancement

#372 Auth / Lock email input & Add persist option
  client/src/App.css
  client/src/components/Auth/EmailForm.module.css
  client/src/components/Auth/EmailForm.tsx
Labels: Frontend, Enhancement

#377 Landing / Create landing page & add auth overlay
  client/package.json
  client/public/assets/images/google.png
  client/public/assets/images/kakao.png
  client/public/assets/images/naver.png
  client/public/images/landing/dual_current_cat.png
  client/public/images/landing/dual_current_kr.png
  client/public/images/landing/dual_scheduled_cat.png
  client/public/images/landing/dual_scheduled_kr.png
  client/public/images/landing/during_bottom.png
  client/public/images/landing/during_top.png
  client/public/images/landing/ring_background.png
  client/public/images/landing/ring_cover.png
  client/public/images/landing/ring_current_cat.png
  client/public/images/landing/ring_frame.png
  client/public/images/landing/ring_root.png
  client/public/images/landing/ring_scheduled_cat.png
  client/public/images/logo.png
  client/src/App.tsx
  client/src/assets/lottie/landing_dual.json
  client/src/assets/lottie/landing_during.json
  client/src/assets/lottie/landing_ring.json
  client/src/components/Auth/Auth.module.css
  client/src/components/Auth/Auth.tsx
  client/src/components/Auth/EmailForm.tsx
  client/src/components/Auth/SNSForm.module.css
  client/src/components/Auth/SNSForm.tsx
  client/src/components/Landing/LandingCarousel.module.css
  client/src/components/Landing/LandingCarousel.tsx
  client/src/components/Landing/LandingItem.module.css
  client/src/components/Landing/LandingItem.tsx
  client/src/layout/ErrorBoundary.tsx
  client/src/layout/RequireAuth.tsx
  client/src/screens/Landing.module.css
  client/src/screens/Landing.tsx
  client/src/screens/Redirect.tsx
  client/src/screens/User.tsx
Labels: Frontend, New Feature

#380 PaymentInput / Add tab - asset, card
  client/src/components/Budget/Input/PaymentInput.module.css
  client/src/components/Budget/Input/PaymentInput.tsx
  client/src/components/UI/Select.tsx
Labels: Frontend, Enhancement

#381 Amount / Use scheduledRemain
  client/src/models/Budget.ts
  client/src/store/total.ts
  client/src/util/api/budgetAPI.ts
Labels: Frontend, Enhancement

#383 TransactionDetail / Fix handler empty transaction on first load
  client/src/components/Budget/Transaction/TransactionDetail.tsx
Labels: Frontend, Bug

#389 UI / Create CurrentTab, update TransactionNav - use isExpense, isIncome in store
  client/src/components/Budget/Input/CategoryInput.tsx
  client/src/components/Budget/Status/CategoryStatus.tsx
  client/src/components/Budget/Status/TotalStatus.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/Budget/Transaction/TransactionLayout.tsx
  client/src/components/Budget/Transaction/TransactionNav.module.css
  client/src/components/Budget/Transaction/TransactionNav.tsx
  client/src/components/Budget/UI/CurrentTab.tsx
  client/src/components/Budget/UI/ExpenseTab.tsx
  client/src/components/User/Category/UserCategorySetting.tsx
  client/src/components/User/Default/DefaultStatus.tsx
  client/src/screens/Budget.tsx
  client/src/screens/InitialSetting.tsx
  client/src/store/ui.ts
Labels: Frontend, Enhancement

#393 fix: Fix 0_FIELD_REQUIRED bug #386
  server/controllers/budgets.ts
  server/controllers/users.ts
Labels: Backend

#407 DateInput / Enable time setting
  client/src/components/Budget/Input/DateInput.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
Labels: Frontend, Enhancement

#408 Modal / Add & use confirm feature
  client/src/components/Asset/Editor/AssetCardEditItemList.tsx
  client/src/components/Asset/Editor/AssetCardItemEditor.tsx
  client/src/components/Auth/Auth.tsx
  client/src/components/Budget/Transaction/TransactionOption.tsx
  client/src/components/UI/DraggableItem.tsx
  client/src/components/UI/Modal.module.css
  client/src/components/UI/Modal.tsx
  client/src/layout/Root.tsx
  client/src/screens/Budget.tsx
  client/src/screens/InitialSetting.tsx
  client/src/screens/NewBudget.tsx
  client/src/screens/User.tsx
  client/src/store/ui.ts
Labels: Frontend, Enhancement

#409 CategoryPlan / Show possible plan amount & Show default in list
  client/src/components/Budget/Category/CategoryPlan.module.css
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Category/CategoryPlanItem.module.css
  client/src/components/Budget/Category/CategoryPlanItem.tsx
Labels: Frontend, Enhancement

#417 TransactionForm / Fix isCurrent bug & payment bug
  client/src/components/Budget/Transaction/TransactionForm.tsx
Labels: Frontend, Bug

#419 fix: TransactionOption / Check if asset exists when dispatch after remove
  client/src/components/Asset/Editor/AssetCardItemEditor.tsx
  client/src/components/Budget/Transaction/TransactionOption.tsx
Labels: Frontend, Bug

#421 BudgetCategorySetting / Use DraggableList (check, edit, remove)
  client/src/components/Budget/Category/BudgetCategorySetting.module.css
  client/src/components/Budget/Category/BudgetCategorySetting.tsx
  client/src/components/Budget/Category/BudgetCategorySettingItem.module.css
  client/src/components/Budget/Category/CategoryAddButton.tsx
  client/src/components/Budget/Category/CategoryCheckItem.tsx
  client/src/components/Budget/Category/CategoryEditItem.tsx
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/UI/DraggableItem.tsx
  client/src/components/UI/OverlayForm.tsx
  client/src/screens/Budget.tsx
  client/src/store/ui.ts
  client/src/util/api/budgetAPI.ts
Labels: Frontend, Enhancement

#422 CategoryPlan / Update default category state
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Category/CategoryPlanItem.tsx
Labels: Frontend, Bug

#424 Amount / Fix available schedule amount #423
  client/src/models/Amount.ts
Labels: Frontend, Bug

#426 OverlayForm / Fix pending not awaited error
  client/src/components/UI/OverlayForm.tsx
  client/src/components/User/Skin/ChartSkinSetting.tsx
Labels: Frontend, Bug

#440 Error / Fix absolute path error & redis version error
  .github/workflows/server-pipeline.yml
  server/_connect.ts
  server/_mongooseConfig/index.ts
  server/_passportConfig/googleStrategy.ts
  server/_passportConfig/guestV2Strategy.ts
  server/_passportConfig/index.ts
  server/_passportConfig/kakaoStrategy.ts
  server/_passportConfig/localStrategy.ts
  server/_passportConfig/localV2Strategy.ts
  server/_passportConfig/naverStrategy.ts
  server/_redisConfig/index.ts
  server/_setup.ts
  server/app.ts
  server/controllers/users.ts
  server/index.ts
  server/jest.config.json
  server/package.json
  server/tsconfig-paths-bootstrap.js
  server/tsconfig.json
Labels: Backend
