Repository during-budget/during-web, pull requests merged in 2023-06, with the labels that each got.

#444 fix: Remove deprecated APIs #394
  server/_passportConfig/index.ts
  server/_passportConfig/localStrategy.ts
  server/controllers/users.ts
  server/routes/users.ts
Labels: Backend

#446 fix: Budget / Update year & month field
  client/src/models/Budget.ts
  client/src/util/api/budgetAPI.ts
Labels: Frontend, Bug

#463 Auth / Update auth redirect url
  server/controllers/auth.ts
Labels: Backend

#465 fix: AmountBars / Hide zero amount bar
  client/src/components/Budget/Amount/AmountBars.tsx
Labels: Frontend, Enhancement

#468 feat: Style / Add responsive layout
  client/src/components/Asset/Status/AssetCardStatus.module.css
  client/src/components/Asset/Status/AssetStatus.module.css
  client/src/components/Asset/Status/CardStatus.module.css
  client/src/components/Budget/Amount/AmountBars.tsx
  client/src/components/Budget/Amount/AmountDetail.module.css
  client/src/components/Budget/Amount/AmountDetail.tsx
  client/src/components/Budget/Amount/AmountDetailItem.module.css
  client/src/components/Budget/Amount/AmountDetailItem.tsx
  client/src/components/Budget/Category/CategoryPlan.module.css
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Category/CategoryPlanItem.module.css
  client/src/components/Budget/Input/EditInput.tsx
  client/src/components/Budget/List/BudgetList.module.css
  client/src/components/Budget/List/BudgetList.tsx
  client/src/components/Budget/Status/TotalStatus.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/Budget/Transaction/TransactionList.tsx
  client/src/components/UI/NavButton.tsx
  client/src/components/UI/Overlay.module.css
  client/src/components/UI/OverlayForm.module.css
  client/src/components/UI/OverlayForm.tsx
  client/src/components/User/Default/DefaultStatus.module.css
  client/src/components/User/Default/DefaultStatus.tsx
  client/src/components/User/Info/Developers.tsx
  client/src/components/User/Info/Privacy.tsx
  client/src/components/User/Setting/SettingItem.tsx
  client/src/components/User/Setting/SettingList.tsx
  client/src/layout/CurrentBudgetNavigator.tsx
  client/src/layout/Nav.tsx
  client/src/screens/Asset.module.css
  client/src/screens/Asset.tsx
  client/src/screens/Budget.module.css
  client/src/screens/Budget.tsx
  client/src/screens/NewBudget.module.css
  client/src/screens/NewBudget.tsx
  client/src/screens/User.module.css
  client/src/screens/User.tsx
  client/src/util/api/authAPI.ts
Labels: Frontend, Enhancement

#473 fix: Reuse email to local login #472
  server/_passportConfig/localV2Strategy.ts
Labels: Backend

#480 fix: TagInput / Enable '#' input
  client/src/components/Budget/Input/TagInput.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
Labels: Frontend, Bug

#481 fix: PaymentInput / Enable only assest when isIncome #459
  client/src/components/Budget/Input/PaymentInput.tsx
  client/src/components/UI/RadioTab.tsx
Labels: Frontend, Bug

#484 User / Enable to update userName
  server/controllers/users.ts
Labels: Backend

#486 feat: Pay / Add prepare & complete payment process
  client/src/components/Payment/PaymentOverlay.module.css
  client/src/components/Payment/PaymentOverlay.tsx
  client/src/components/User/Skin/ChartSkinSetting.tsx
  client/src/store/ui.ts
  client/src/util/api/itemAPI.ts
  client/src/util/api/paymentAPI.ts
Labels: Frontend, New Feature

#487 feat: DateSelector / Add dateSelector for basic budget
  client/src/components/Budget/Input/DateInput.tsx
  client/src/components/Budget/Input/DateSelector.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
Labels: Frontend, Enhancement

#488 fix: AmountInput / Handle focus & blur on 0 value
  client/src/components/Asset/Editor/AssetFields.tsx
  client/src/components/Budget/Input/EditInput.tsx
Labels: Frontend, Enhancement

#493 feat: Init / Focus planEditor when setting default budget
  client/src/components/Budget/Amount/AmountDetailItem.tsx
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Input/EditInput.tsx
  client/src/components/User/Default/DefaultStatus.module.css
  client/src/components/User/Default/DefaultStatus.tsx
Labels: Frontend, Enhancement

#503 ChartSkin / Lock when unpaid
  client/src/components/Asset/Status/CardStatus.tsx
  client/src/components/Budget/Amount/AmountRing.tsx
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/User/Skin/ChartSkinSetting.module.css
  client/src/components/User/Skin/ChartSkinSetting.tsx
  client/src/screens/Landing.tsx
  client/src/screens/User.tsx
  client/src/store/setting.ts
  client/src/store/user.ts
  client/src/util/api/settingAPI.ts
  client/src/util/api/userAPI.ts
Labels: Frontend, Enhancement

#507 Settings / Fix USetting* API bug
  server/controllers/settings.ts
Labels: Backend, Bug

#509 PaymentOverlay / Add refund policy
  client/src/components/Payment/PaymentOverlay.module.css
  client/src/components/Payment/PaymentOverlay.tsx
Labels: Frontend, Enhancement

#515 User / Implement theme settings
  server/controllers/settings.ts
  server/models/User.ts
Labels: Backend

#517 Transactions / Enable to find by tag
  server/controllers/transactions.ts
Labels: Backend

#519 User / change default chartSkin setting basic to cat
  server/controllers/settings.ts
  server/models/_basicSettings.ts
Labels: Backend

#522 fix: CategoryPlan / Fix category plan input showing previous input
  client/src/components/Budget/Category/CategoryPlanItem.tsx
Labels: Bug
