Repository during-budget/during-web, pull requests merged in 2023-03, with the labels that each got.

#140 137 category update api
  server/controllers/categories.js
  server/models/User.js
  server/routes/categories.js
  server/utils/compareById.js
Labels: Backend

#146 143 budget default category
  server/controllers/budgets.js
  server/models/Budget.js
Labels: Backend

#155 feat: Replace field 'userName' with 'email' #132
  server/controllers/users.js
  server/models/User.js
  server/passport/localStrategy.js
  server_db/src/pages/UserPage/List.js
Labels: Backend

#165 feat: Remove transactions when budget is removed #163
  server/controllers/budgets.js
Labels: Backend

#166 feat: Update related docs when removing doc #164
  server/controllers/budgets.js
  server/controllers/test.js
  server/controllers/transactions.js
  server/routes/test.js
  server_db/src/pages/BudgetPage/List.js
Labels: Backend

#187 fix: Update transaction amount update API #186
  server/controllers/transactions.js
Labels: Backend, Bug

#189 feat: DateStatus / Implement view, add action #118
  client/src/components/Budget/Status/DateStatus.tsx
Labels: Frontend, New Feature

#193 feat: Transaction / Scroll when created, view other transaction
  client/src/components/Budget/Transaction/TransactionForm.tsx
  client/src/components/Budget/Transaction/TransactionOption.tsx
  client/src/util/api/transactionAPI.ts
Labels: Frontend, Enhancement

#200 User / Add fields('birthdate', 'gender', 'tel') to user model and create update API
  server/controllers/users.ts
  server/models/User.ts
  server/routes/users.ts
Labels: Backend, Enhancement

#211 feat: Transition / Update transition using cubic-bezier
  client/src/App.css
  client/src/components/Budget/Amount/AmountBar.module.css
  client/src/components/Budget/Amount/AmountBars.module.css
  client/src/components/Budget/Amount/AmountRing.module.css
  client/src/components/Budget/Chart/GroupedBar.module.css
  client/src/components/Budget/Transaction/TransactionDetail.tsx
  client/src/components/Budget/Transaction/TransactionForm.module.css
  client/src/components/UI/InputField.module.css
  client/src/components/UI/Overlay.module.css
  client/src/components/UI/Select.module.css
  client/src/store/transaction.ts
Labels: Frontend, Enhancement
