Repository during-budget/during-web, pull requests merged in 2023-07, with the labels that each got.

#530 User / Implement theme setting validation
  server/controllers/settings.ts
  server/models/User.ts
  server/models/_basicSettings.ts
Labels: Backend

#539 User / Update single category C/U APIs
  server/controllers/categories.ts
Labels: Backend

#546 Budget / implement autoPlanned feature
  client_admin/src/pages/UserBudgetPage/tab/Categories.js
  server/models/Budget.ts
Labels: Backend

#548 feat: AmountBars / Update amount bar as vertical bar chart #541
  client/src/components/Budget/Amount/AmountBars.module.css
  client/src/components/Budget/Amount/AmountBars.tsx
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Category/CategoryPlanItem.tsx
Labels: Frontend, Enhancement

#551 fix: AmountInput / Handler input not exists #550
  client/src/components/Budget/Category/CategoryPlan.tsx
  client/src/components/Budget/Input/AmountInput.tsx
  client/src/components/Budget/Input/AmountOverlay.tsx
  client/src/components/Budget/Input/EditInput.tsx
  client/src/components/User/Default/DefaultStatus.tsx
Labels: Frontend, Bug

#552 feat: BudgetHeader / Add delete option #479
  client/src/components/Budget/Category/CategoryDetail.tsx
  client/src/components/Budget/Transaction/TransactionOption.tsx
  client/src/components/Budget/UI/BudgetHeader.module.css
  client/src/components/Budget/UI/BudgetHeader.tsx
  client/src/components/User/Default/DefaultStatus.tsx
  client/src/screens/Budget.tsx
  client/src/util/api/budgetAPI.ts
Labels: Frontend, New Feature

#555 ReactNative / Create webview app & update back button actions #553
  app/during/app.json
  app/during/ios/Podfile.lock
  app/during/ios/during.xcodeproj/project.pbxproj
  app/during/package.json
  app/during/src/screens/Main.tsx
  app/during/yarn.lock
Labels: New Feature, App

#569 Auth / Fix sending email bug
  server/package.json
Labels: Backend, Bug

#571 Feat: Store / Set store page #563
  client/src/App.tsx
  client/src/components/Budget/Amount/AmountRing.tsx
  client/src/components/Store/AdRemove.module.css
  client/src/components/Store/AdRemove.tsx
  client/src/components/User/Skin/ChartSkinList.tsx
  client/src/components/User/Skin/ChartSkinSetting.module.css
  client/src/components/User/Skin/ChartSkinSetting.tsx
  client/src/layout/Nav.tsx
  client/src/layout/Root.tsx
  client/src/screens/Store.module.css
  client/src/screens/Store.tsx
  client/src/screens/User.tsx
  client/src/store/ui.ts
Labels: Frontend, New Feature

#575 Payment / create DPayment API
  client_admin/src/pages/UserPage/tab/Payments.js
  server/controllers/payments.ts
  server/routes/payments.ts
Labels: Backend
